### ISSUE TITLE
Initial setup procedure/script not complete

### ISSUE THREAD

**Issue by obieler** [epfl-si/wp-dev#67]
**Description**

The initial setup step `make checkout`:
https://github.com/epfl-si/wp-dev/blob/e7d17b0cc036a3cc97721bc2dfc3e2b2d2d02b5b/README.md?plain=1#L17 
needs to have (I believe) as a prerequisite:

1. `eyaml` installed >= 3.2.0
2. The 'suitcase' installed

**Comment by jdelasoie** [comment]
In fact, having the suitcase should be enough, as it provides the necessary `eyaml`

**Comment by domq** [comment]
Hello dear colleagues, would you be so kind as to schedule a 1-hour meeting with me to sort this out together?

**Comment by domq** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1629585/174551453-2a9a64cf-7299-4853-8f34-23f22563a74f.png">
Do we get this message out of a fresh `make checkout`, or not?

**Comment by obieler** [comment]
> Do we get this message out of a fresh `make checkout`, or not?
To my memory i don't think so

**Comment by jdelasoie** [comment]
Btw, in case, I have added some information about this problem directly in the readme Ln 11 https://github.com/epfl-si/wp-dev/commit/4ff17be09e34677ef5ea7e4a6c81003d6c7b16ac

**Comment by domq** [comment]
I can reproduce the issue, and in my case it was due to a broken `/usr/local/bin/eyaml` (caused by upgrading Ruby without reinstalling all the gems).

**Comment by ponsfrilus** [comment]
@obieler what's the follow up on this?
